name: skale
description: SKALE.dart - A community built and maintained library for Dart & Flutter Projects building on SKALE Network
version: 0.1.0 
repository: https://github.com/Dirt-Road-Development/skale.dart

environment:
  sdk: '>=2.19.2 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  convert: ^3.1.1
  eth_sig_util: ^0.0.9
  http: ^0.13.6
  web3dart: ^2.6.1
